name: Loki

on: [pull_request]

jobs:
  run-loki:
    name: Run Loki
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GP_TOKEN }}" >> .npmrc
          echo "@refrens:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run loki
        run: npm run loki:ci
